// Every route the assembled api serves, under the server's /api prefix.
//
// A path is the only thing that lives longer than the code behind it, so this
// table is the contract: a rename has to be made here in the same change, and
// two suites read it rather than each keeping a copy. The oRPC surface checks
// it is complete; the Effect port checks it invents nothing.

export const FROZEN_ROUTES = [
  'DELETE /auth/session',
  'GET /auth/login-methods',
  'GET /auth/session',
  'POST /auth/local/{providerCode}/login',

  'GET /app/manifest',

  'GET /iam/permissions',
  'POST /iam/access-evaluations',
  'GET /iam/role-options',
  'GET /iam/roles',
  'POST /iam/roles',
  'GET /iam/roles/{roleId}',
  'PATCH /iam/roles/{roleId}',
  'DELETE /iam/roles/{roleId}',
  'GET /iam/roles/{roleId}/eligibility',
  'PUT /iam/roles/{roleId}/eligibility',
  'GET /iam/roles/{roleId}/permissions',
  'PUT /iam/roles/{roleId}/permissions',
  'PUT /iam/roles/{roleId}/status',
  'GET /iam/role-grants',
  'POST /iam/role-grants',
  'DELETE /iam/role-grants/{grantId}',
  'GET /iam/role-grant-options',

  'GET /iam/user-options',
  'GET /iam/user-type-options',
  'GET /iam/user-types',
  'POST /iam/user-types',
  'GET /iam/user-types/{userTypeId}',
  'PATCH /iam/user-types/{userTypeId}',
  'DELETE /iam/user-types/{userTypeId}',
  'GET /iam/user-types/{userTypeId}/placement-policy',
  'PUT /iam/user-types/{userTypeId}/placement-policy',
  'PUT /iam/user-types/{userTypeId}/status',

  'GET /iam/users',
  'POST /iam/users',
  'GET /iam/users/{userId}',
  'PATCH /iam/users/{userId}',
  'PUT /iam/users/{userId}/placement',
  'PUT /iam/users/{userId}/status',
  'GET /iam/users/{userId}/effective-permissions',
  'GET /iam/users/{userId}/role-grants',

  'GET /assessment/batches',
  'POST /assessment/batches',
  'GET /assessment/batches/{batchId}',
  'PATCH /assessment/batches/{batchId}',
  'DELETE /assessment/batches/{batchId}',
  'PUT /assessment/batches/{batchId}/status',
  'GET /assessment/batches/{batchId}/access',
  'POST /assessment/batches/{batchId}/access',
  'GET /assessment/batches/{batchId}/staff-options',
  'GET /assessment/batches/{batchId}/access/sync',
  'POST /assessment/batches/{batchId}/access/sync',
  'PUT /assessment/batches/{batchId}/access/{userId}/permissions/{permission}',
  'DELETE /assessment/batches/{batchId}/access/sources/{sourceId}',
  'GET /assessment/batches/{batchId}/phases',
  'PUT /assessment/batches/{batchId}/phases',
  'PUT /assessment/batches/{batchId}/phases/{phaseId}/schedule',
  'PUT /assessment/batches/{batchId}/phase',
  'GET /assessment/batches/{batchId}/timeline',
  'GET /assessment/batches/{batchId}/participants',
  'POST /assessment/batches/{batchId}/participants',
  'GET /assessment/batches/{batchId}/import-candidates',
  'GET /assessment/batches/{batchId}/participant-imports',
  'POST /assessment/batches/{batchId}/participant-imports',
  'PUT /assessment/batches/{batchId}/participants/{participantId}/status',
  'GET /assessment/batches/{batchId}/my-result',
  'GET /assessment/review/inbox',
  'GET /assessment/review/instances/{instanceId}',
  'POST /assessment/review/instances/{instanceId}/decisions',
  'POST /assessment/attachments/uploads',
  'POST /assessment/attachments/uploads/{reservationId}/complete',
  'GET /assessment/attachments/{attachmentId}',
  'GET /assessment/attachments/{attachmentId}/content',
  'GET /assessment/batches/{batchId}/my-entries',
  'GET /assessment/entries/{entryId}/revisions',
  'POST /assessment/entries',
  'GET /assessment/entries/{entryId}',
  'POST /assessment/entries/{entryId}/revisions',
  'PUT /assessment/entries/{entryId}/status',
  'POST /assessment/entries/{entryId}/interventions',
  'GET /assessment/batches/{batchId}/items',
  'POST /assessment/batches/{batchId}/items',
  'GET /assessment/items/{itemId}',
  'GET /assessment/batches/{batchId}/item-options',
  'GET /assessment/batches/{batchId}/review-alerts',
  'GET /assessment/batches/{batchId}/review-coverage',
  'DELETE /assessment/items/{itemId}',
  'PUT /assessment/items/{itemId}/status',
  'PATCH /assessment/items/{itemId}',
  'GET /assessment/batches/{batchId}/score-groups',
  'PUT /assessment/batches/{batchId}/score-groups',
  'GET /assessment/scope-options',
  'GET /assessment/user-type-options',
  'GET /assessment/phase-templates',
  'POST /assessment/phase-templates',
  'PATCH /assessment/phase-templates/{templateId}',
  'DELETE /assessment/phase-templates/{templateId}',

  'GET /org/tree',
  'GET /org/types',
  'POST /org/types',
  'PATCH /org/types/{typeId}',
  'DELETE /org/types/{typeId}',
  'GET /org/type-rules',
  'PUT /org/type-rules/{parentTypeId}/{childTypeId}',
  'DELETE /org/type-rules/{parentTypeId}/{childTypeId}',
  'GET /org/nodes/{nodeId}',
  'POST /org/nodes',
  'PATCH /org/nodes/{nodeId}',
  'DELETE /org/nodes/{nodeId}',
  'PUT /org/nodes/{nodeId}/placement',
  'PUT /org/nodes/{nodeId}/type',

  'GET /ping/hello',
]
