import { eq, sql } from 'drizzle-orm'
import { Effect, Exit, Layer, Schema, Scope } from 'effect'
import { describe, expect, it } from 'vitest'
import { createTestContext, postgresAvailable } from '@qualy/plugin-database/testkit'
import { orgNodes, orgTypes, tenants } from '@qualy/plugin-org/schema'
import { Database, databaseLayer } from '../src/index.ts'

// M1: does the Effect stack carry THIS project's database?
//
// The upstream integration tests prove effect-postgres works. They prove it
// against plain `pgTable` on a schema someone wrote for the test. What is
// unverified is the part that matters here: this repository's schema uses the
// `snakeCase.*` builders, uuidv7 defaults generated by PG18, an ltree column
// and constraints whose names the authorization layer translates into domain
// errors. None of that appears in any upstream test.
//
// The scratch database, its lineage and its teardown stay with the plugin that
// owns them. This suite only points an Effect client at a database that
// already exists, which is also the shape the real migration would take.

const run = <A, E>(url: string, effect: Effect.Effect<A, E, Database>) =>
  Effect.runPromiseExit(Effect.provide(effect, databaseLayer(url)))

const expectSuccess = <A, E>(exit: Exit.Exit<A, E>): A => {
  if (Exit.isSuccess(exit)) return exit.value
  throw new Error(`expected success, got: ${JSON.stringify(exit.cause)}`)
}

/** the shape a driver failure actually arrives in, walked by hand for the spike */
interface Cause {
  reasons?: ReadonlyArray<{
    error?: {
      _tag?: string
      reason?: { _tag?: string; cause?: { code?: string; constraint?: string } }
    }
  }>
}

const failureOf = <A, E>(exit: Exit.Exit<A, E>): { _tag?: string; cause?: unknown } => {
  if (Exit.isSuccess(exit)) throw new Error('expected a failure')
  const reason = (exit.cause as unknown as Cause).reasons?.[0]
  return (reason as { error?: { _tag?: string; cause?: unknown } })?.error ?? {}
}

class Rejected extends Schema.ErrorClass<Rejected>('Rejected')({}) {}

describe.runIf(postgresAvailable).concurrent('effect-postgres against the real schema', () => {
  it('reads a snakeCase table, an ltree column and a PG18 uuidv7 default', async () => {
    const db = await createTestContext('effect-spike-schema')
    try {
      // seed through the existing path, so the row is exactly what production
      // writes: uuidv7 from the column default, ltree path, timestamptz
      await db.query(
        `insert into tenants (slug, name) values ('spike', 'Spike') returning id`,
      )
      const tenant = await db.row<{ id: string }>(`select id from tenants limit 1`)
      await db.query(
        `insert into org_types (tenant_id, code, name, sort_order) values ($1, 'root', 'Root', 10)`,
        [tenant.id],
      )
      const type = await db.row<{ id: string }>(`select id from org_types limit 1`)
      await db.query(
        `insert into org_nodes (tenant_id, org_type_id, code, name, depth, path)
         values ($1, $2, 'r', 'Root', 0, replace($3::text, '-', '')::ltree)`,
        [tenant.id, type.id, tenant.id],
      )

      const exit = await run(
        db.url,
        Effect.gen(function* () {
          const drizzle = yield* Database
          const rows = yield* drizzle
            .select({
              id: orgNodes.id,
              code: orgNodes.code,
              createdAt: orgNodes.createdAt,
              path: sql<string>`${orgNodes.path}::text`,
            })
            .from(orgNodes)
          return rows
        }),
      )

      const rows = expectSuccess(exit)
      expect(rows).toHaveLength(1)
      // uuidv7 is generated by the column default, so reading it back proves
      // the PG18 function is reachable through this driver
      expect(rows[0]!.id).toMatch(/^[0-9a-f-]{36}$/)
      expect(rows[0]!.path).toMatch(/^[0-9a-f]{32}$/)
      // BEHAVIOUR CHANGE from node-postgres: timestamptz comes back as a Date,
      // not a string. Existing assertions that check the value as a string
      // will have to change.
      expect(rows[0]!.createdAt).toBeInstanceOf(Date)
    } finally {
      await db.dispose()
    }
  })

  it('rolls back a write when the transaction body fails with a typed error', async () => {
    // the whole reason for the migration: a domain failure after a write must
    // undo the write, without anyone remembering to catch and rethrow
    const db = await createTestContext('effect-spike-rollback')
    try {
      let seenInsideTransaction = 0
      const exit = await run(
        db.url,
        Effect.gen(function* () {
          const drizzle = yield* Database
          return yield* drizzle.transaction((tx) =>
            Effect.gen(function* () {
              yield* tx.insert(tenants).values({ slug: 'rolled-back', name: 'Rolled back' })
              // proving the write really happened before the failure: without
              // this the assertion below passes just as well when the insert
              // never ran at all
              const inside = yield* tx
                .select({ slug: tenants.slug })
                .from(tenants)
                .where(eq(tenants.slug, 'rolled-back'))
              seenInsideTransaction = inside.length
              return yield* new Rejected()
            }),
          )
        }),
      )

      expect(seenInsideTransaction).toBe(1)
      expect(Exit.isFailure(exit)).toBe(true)
      const after = await db.row<{ count: number }>(
        `select count(*)::int as count from tenants where slug = 'rolled-back'`,
      )
      expect(after.count).toBe(0)
    } finally {
      await db.dispose()
    }
  })

  it('commits when the body succeeds', async () => {
    const db = await createTestContext('effect-spike-commit')
    try {
      const exit = await run(
        db.url,
        Effect.gen(function* () {
          const drizzle = yield* Database
          return yield* drizzle.transaction((tx) =>
            tx.insert(tenants).values({ slug: 'kept', name: 'Kept' }),
          )
        }),
      )
      expectSuccess(exit)
      const after = await db.row<{ count: number }>(
        `select count(*)::int as count from tenants where slug = 'kept'`,
      )
      expect(after.count).toBe(1)
    } finally {
      await db.dispose()
    }
  })

  it('rolls back an interrupted transaction', async () => {
    // provable from the source (commit is decided by Exit.isSuccess) but no
    // upstream test interrupts one, and this is the case a request timeout or
    // a client disconnect produces
    const db = await createTestContext('effect-spike-interrupt')
    try {
      const exit = await run(
        db.url,
        Effect.gen(function* () {
          const drizzle = yield* Database
          return yield* drizzle.transaction((tx) =>
            Effect.gen(function* () {
              yield* tx.insert(tenants).values({ slug: 'interrupted', name: 'Interrupted' })
              return yield* Effect.interrupt
            }),
          )
        }),
      )

      expect(Exit.isSuccess(exit)).toBe(false)
      const after = await db.row<{ count: number }>(
        `select count(*)::int as count from tenants where slug = 'interrupted'`,
      )
      expect(after.count).toBe(0)
    } finally {
      await db.dispose()
    }
  })

  it('nests a transaction as a savepoint and rolls back only the inner one', async () => {
    // the outer write must survive an inner failure. Also worth knowing: the
    // savepoint is never RELEASEd on success, so a long outer transaction
    // accumulates them.
    const db = await createTestContext('effect-spike-savepoint')
    try {
      const exit = await run(
        db.url,
        Effect.gen(function* () {
          const drizzle = yield* Database
          return yield* drizzle.transaction((tx) =>
            Effect.gen(function* () {
              yield* tx.insert(tenants).values({ slug: 'outer', name: 'Outer' })
              // the inner failure is caught here, so the outer transaction
              // still exits successfully and commits
              yield* Effect.result(
                tx.transaction((inner) =>
                  Effect.gen(function* () {
                    yield* inner.insert(tenants).values({ slug: 'inner', name: 'Inner' })
                    return yield* new Rejected()
                  }),
                ),
              )
            }),
          )
        }),
      )

      expectSuccess(exit)
      const outer = await db.row<{ count: number }>(
        `select count(*)::int as count from tenants where slug = 'outer'`,
      )
      const inner = await db.row<{ count: number }>(
        `select count(*)::int as count from tenants where slug = 'inner'`,
      )
      expect(outer.count).toBe(1)
      expect(inner.count).toBe(0)
    } finally {
      await db.dispose()
    }
  })

  it('leaves an unrecognised sql error as an infrastructure failure', async () => {
    // a syntax error or a missing relation must not arrive looking like a
    // business conflict that a handler might map to a 409
    const db = await createTestContext('effect-spike-unknown-sql')
    try {
      const exit = await run(
        db.url,
        Effect.gen(function* () {
          const drizzle = yield* Database
          return yield* drizzle.execute(sql`select * from a_table_that_does_not_exist`)
        }),
      )

      expect(Exit.isFailure(exit)).toBe(true)
      const queryError = failureOf(exit)
      const sqlError = (queryError.cause as Cause)?.reasons?.[0]?.error
      // 42P01 undefined_table: classified as a plain SqlError, NOT as one of
      // the constraint reasons a domain translator looks at
      expect(sqlError?.reason?.cause?.code).toBe('42P01')
      expect(sqlError?.reason?._tag).not.toBe('UniqueViolation')
      expect(sqlError?.reason?._tag).not.toBe('ConstraintError')
    } finally {
      await db.dispose()
    }
  })

  it('still carries the constraint name a unique violation reports', async () => {
    // authorization and the cross-plugin invariants translate constraint names
    // into domain errors. If the name does not survive the Effect error
    // wrapping, createConstraintTranslator has nothing to match on.
    //
    // It survives, but four levels down, and the shape is worth writing out
    // because the rewritten translator has to walk exactly this:
    //
    //   EffectDrizzleQueryError { query, params }
    //     .cause                        -> an Effect Cause, not a driver error
    //       .reasons[0].error           -> SqlError
    //         .reason                   -> pre-classified by @effect/sql-pg
    //           ._tag === 'UniqueViolation'
    //           .cause                  -> the raw pg error, with code + constraint
    const db = await createTestContext('effect-spike-constraint')
    try {
      await db.query(`insert into tenants (slug, name) values ('dup', 'Dup')`)
      const exit = await run(
        db.url,
        Effect.gen(function* () {
          const drizzle = yield* Database
          return yield* drizzle.insert(tenants).values({ slug: 'dup', name: 'Dup again' })
        }),
      )

      expect(Exit.isFailure(exit)).toBe(true)
      const queryError = failureOf(exit)
      expect(queryError._tag).toBe('EffectDrizzleQueryError')
      const sqlError = (queryError.cause as Cause)?.reasons?.[0]?.error
      expect(sqlError?._tag).toBe('SqlError')
      expect(sqlError?.reason?._tag).toBe('UniqueViolation')
      expect(sqlError?.reason?.cause?.code).toBe('23505')
      expect(sqlError?.reason?.cause?.constraint).toBe('tenants_slug_key')
    } finally {
      await db.dispose()
    }
  })

  it('closes the pool when the scope closes', async () => {
    // the shutdown property the whole runtime rests on: no finalizer, no
    // graceful SIGTERM
    const db = await createTestContext('effect-spike-shutdown')
    const connections = async () =>
      (
        await db.row<{ count: number }>(
          `select count(*)::int as count from pg_stat_activity where datname = current_database()`,
        )
      ).count
    try {
      const before = await connections()
      let during = 0

      await Effect.runPromise(
        Effect.gen(function* () {
          const scope = yield* Scope.make()
          const context = yield* Layer.buildWithScope(databaseLayer(db.url), scope)
          yield* Effect.provideContext(
            Effect.gen(function* () {
              const drizzle = yield* Database
              yield* drizzle.select({ one: sql<number>`1` }).from(tenants)
              during = yield* Effect.promise(connections)
            }),
            context,
          )
          yield* Scope.close(scope, Exit.void)
        }),
      )

      // the layer really did open its own connection, and closing the scope
      // really did take it away. Asserting only the second half would pass
      // against a layer that never connected.
      expect(during).toBeGreaterThan(before)
      // postgres reaps a backend a moment after the client goes away, so the
      // count is polled rather than sampled once. It still has to reach the
      // baseline: a pool that never closed would keep failing this.
      let settled = await connections()
      for (let attempt = 0; attempt < 50 && settled > before; attempt += 1) {
        await new Promise((resolve) => setTimeout(resolve, 20))
        settled = await connections()
      }
      expect(settled).toBe(before)
    } finally {
      await db.dispose()
    }
  })
})
