import path from 'node:path'
import YAML from 'yaml'
import { shortId } from './hash.ts'
import { writeAtomic } from './lock.ts'
import type { Resolution } from './resolve.ts'

// What the host loads, derived from the manifest.
//
// Two shapes exist while the runtime is being replaced. The cordis loader
// reads a flat entry list, so `cordis.gen.yml` translates the keyed manifest
// into one. The Effect runtime reads a TypeScript module instead, because a
// static import is worth more than a resolved string: a missing package fails
// the build rather than the boot, a bundler can see what is reachable, and the
// composed layer is typechecked before anything runs.
//
// Entry ids in the cordis file are derived from the plugin id rather than
// generated, so the loader has no reason to write ids back into it.

export interface RuntimeEntry {
  id: string
  name: string
  config?: unknown
}

export function runtimeEntries(resolution: Resolution): RuntimeEntry[] {
  return resolution.runtimePlugins.map((id) => {
    const config = resolution.manifest.plugins.get(id)?.config
    return config === undefined
      ? { id: shortId(id), name: id }
      : { id: shortId(id), name: id, config }
  })
}

export function renderRuntimePlan(resolution: Resolution): string {
  const banner = [
    `# Generated by Qualy from ${path.basename(resolution.manifest.source)}. Run 'pnpm gen' to regenerate.`,
    '# Do not edit this file by hand, it will be overwritten.',
    '',
  ].join('\n')
  return banner + YAML.stringify(runtimeEntries(resolution), { lineWidth: 0 })
}

export const writeRuntimePlan = (file: string, resolution: Resolution): boolean =>
  writeAtomic(file, renderRuntimePlan(resolution))

/**
 * The plugins that ship an Effect runtime, in the order the module imports them.
 *
 * A plugin says so with `qualy.runtime.entry` in its package.json, naming one
 * of its own subpath exports. Declaring it there rather than in code is what
 * lets resolution stay a file-reading operation: the assembly decides what an
 * application contains without importing any of it.
 */
export const runtimeLayers = (resolution: Resolution) =>
  resolution.runtimePlugins.flatMap((id) => {
    const entry = resolution.resolver.readMetadata(id).runtime?.entry
    return entry ? [{ id, specifier: `${id}/${entry.replace(/^\.\//, '')}` }] : []
  })

const identifier = (id: string) =>
  id
    .replace(/^@[^/]+\//, '')
    .replace(/[^a-zA-Z0-9]+(.)/g, (_match, next: string) => next.toUpperCase())

/**
 * The generated composition root.
 *
 * A list of imports and one merged layer, deliberately nothing else: anything
 * conditional belongs in resolution, which has already run by the time this
 * file exists.
 */
export function renderRuntimeModule(resolution: Resolution): string {
  const layers = runtimeLayers(resolution)
  const imports = layers.map(
    (layer) => `import { layer as ${identifier(layer.id)} } from '${layer.specifier}'`,
  )
  return [
    `// Generated by Qualy from ${path.basename(resolution.manifest.source)}. Run 'pnpm gen' to regenerate.`,
    '// Do not edit this file by hand, it will be overwritten.',
    "import { Layer } from 'effect'",
    ...imports,
    '',
    '/** every plugin in this assembly that ships an Effect runtime */',
    layers.length > 0
      ? `export const pluginLayers = Layer.mergeAll(\n${layers
          .map((layer) => `  ${identifier(layer.id)},`)
          .join('\n')}\n)`
      : 'export const pluginLayers = Layer.empty',
    '',
  ].join('\n')
}

export const writeRuntimeModule = (file: string, resolution: Resolution): boolean =>
  writeAtomic(file, renderRuntimeModule(resolution))
