import path from 'node:path'
import YAML from 'yaml'
import { shortId } from './hash.ts'
import { writeAtomic } from './lock.ts'
import type { Resolution } from './resolve.ts'

// The cordis loader reads a flat list of entries; the manifest is a keyed map
// of a product selection. This is the translation between them, and it is the
// piece a purpose-built assembly loader would replace.
//
// Entry ids are derived from the plugin id rather than generated, so the file
// is a pure function of the manifest: the loader has no reason to write ids
// back into it, and regenerating it produces the same bytes.

export interface RuntimeEntry {
  id: string
  name: string
  config?: unknown
}

export function runtimeEntries(resolution: Resolution): RuntimeEntry[] {
  return resolution.runtimePlugins.map((id) => {
    const config = resolution.manifest.plugins.get(id)?.config
    return config === undefined
      ? { id: shortId(id), name: id }
      : { id: shortId(id), name: id, config }
  })
}

export function renderRuntimePlan(resolution: Resolution): string {
  const banner = [
    `# Generated by Qualy from ${path.basename(resolution.manifest.source)}. Run 'pnpm gen' to regenerate.`,
    '# Do not edit this file by hand, it will be overwritten.',
    '',
  ].join('\n')
  return banner + YAML.stringify(runtimeEntries(resolution), { lineWidth: 0 })
}

export const writeRuntimePlan = (file: string, resolution: Resolution): boolean =>
  writeAtomic(file, renderRuntimePlan(resolution))
