import fs from 'node:fs'
import path from 'node:path'

// reserved for contracts/plugins generators (P0 sessions 5/7), do not remove

export function writeGenerated(
  file: string,
  body: string,
  options: { source?: string } = {},
): void {
  const banner = [
    `// Generated by Qualy codegen from ${options.source ?? 'cordis.yml'}. Run 'pnpm gen' to regenerate.`,
    '// Do not edit this file by hand, it will be overwritten.',
    '',
  ].join('\n')
  const content = banner + body.trimEnd() + '\n'
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === content) {
    console.log(`${file} unchanged, skipped`)
    return
  }
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, content)
  console.log(`${file} written`)
}
