import fs from 'node:fs'
import path from 'node:path'
import { generatedPath } from './paths.ts'
import { report } from './report.ts'

/**
 * Write a generated artifact, named by its repository-relative path.
 *
 * The path is resolved against the output root rather than the working
 * directory, so a test can generate a different selection into a throwaway
 * tree instead of over the one other suites are reading.
 */
export function writeGenerated(
  relative: string,
  body: string,
  options: { source?: string } = {},
): void {
  const file = generatedPath(relative)
  const banner = [
    `// Generated by Qualy codegen from ${options.source ?? 'qualy.yml'}. Run 'pnpm gen' to regenerate.`,
    '// Do not edit this file by hand, it will be overwritten.',
    '',
  ].join('\n')
  const content = banner + body.trimEnd() + '\n'
  // silence is the common case and the useful one: nine "unchanged" lines
  // before every start say only that codegen ran, which the caller knows
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === content) return
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, content)
  report(`generated ${relative}`)
}
