import fs from 'node:fs'
import path from 'node:path'

import { markGeometry } from '../../packages/web/brand/src/geometry.ts'
import { openJost, solveWeight } from './font.ts'
import { RING_TO_CAP, TAIL_GAP, TOLERANCE, TRACKING, WORDMARK_S } from './spec.ts'
import { layoutWordmark, ringOf } from './wordmark.ts'

// Draws the brand assets: the wordmark's frozen outlines as a data module,
// and the two static SVGs. A design tool rather than a build step - what it
// writes is reviewed and committed like an export from a drawing program,
// and nothing checks that running it again produces no diff (docs/brand.md).

const ROOT = path.resolve(import.meta.dirname, '../..')
const BRAND = path.join(ROOT, 'packages/web/brand')

const jost = await openJost()
const weight = solveWeight(jost.font)
const layout = layoutWordmark(jost.font, {
  wght: weight.wght,
  s: WORDMARK_S,
  tailGap: TAIL_GAP,
  tracking: TRACKING,
})
const ring = ringOf(layout)
const mark = markGeometry()

const quoted = (text: string) => `'${text}'`

const dataModule = `// Generated by \`pnpm brand:generate\` (tools/brand/generate.ts): change the
// generator or its parameters in tools/brand/spec.ts, not this file.
//
// Letters u a l y: Jost ${jost.fontVersion} from @fontsource-variable/jost
// ${jost.packageVersion}, instance wght ${weight.wght}, no OpenType features, read from
// ${jost.file}.
// Jost is published under the SIL Open Font License 1.1; these outlines are
// artwork derived from it, not a font.
//
// Layout: s = ${layout.s} (the stem of the l), cap height ${layout.capHeight}, tail
// clearance ${TAIL_GAP}s, tracking ${TRACKING}em, baseline at y = 0.

export const wordmark = {
  viewBox: ${quoted(layout.viewBox)},
  s: ${layout.s},
  capHeight: ${layout.capHeight},
  ringCenter: { x: ${layout.ringCenter.x}, y: ${layout.ringCenter.y} },
  letters: [
${layout.letters
  .map(
    (letter) => `    {\n      char: ${quoted(letter.char)},\n      d: ${quoted(letter.d)},\n    },`,
  )
  .join('\n')}
  ],
} as const
`

const svg = (viewBox: string, body: string[]) =>
  [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" fill="currentColor">`,
    ...body.map((line) => `  ${line}`),
    '</svg>',
    '',
  ].join('\n')

const markSvg = svg(mark.viewBox, [
  '<title>Qualy</title>',
  `<path d="${mark.ring}"/>`,
  `<path d="${mark.piece}"/>`,
])

const wordmarkSvg = svg(layout.viewBox, [
  `<!-- letters: Jost ${jost.fontVersion} (SIL Open Font License 1.1) at wght ${weight.wght}, as outlines -->`,
  '<title>Qualy</title>',
  `<path d="${ring.ring}"/>`,
  `<path d="${ring.piece}"/>`,
  ...layout.letters.map((letter) => `<path d="${letter.d}"/>`),
])

const written = [
  ['src/wordmark-paths.ts', dataModule],
  ['assets/mark.svg', markSvg],
  ['assets/wordmark.svg', wordmarkSvg],
] as const
for (const [file, content] of written) {
  fs.writeFileSync(path.join(BRAND, file), content)
}

const percent = (fraction: number) => `${(fraction * 100).toFixed(2)}%`
console.log(
  `brand: Jost ${jost.fontVersion} (@fontsource-variable/jost ${jost.packageVersion}, ${jost.file})`,
)
console.log(
  `brand: wght ${weight.wght}: stem ${weight.stem} / cap height ${weight.capHeight} font units; ring height is ${weight.ratio.toFixed(4)} cap heights (target ${RING_TO_CAP}, off by ${percent(weight.error)})`,
)
if (Math.abs(weight.error) > TOLERANCE) {
  console.log(
    `brand: no weight in range comes within ${percent(TOLERANCE)}; stem matched first, ring overshoot reported above`,
  )
}
console.log(
  `brand: s = ${layout.s} wordmark units (${layout.scale.toFixed(5)} per font unit); cap height ${layout.capHeight}; ring centre ${layout.ringCenter.x}, ${layout.ringCenter.y}`,
)
console.log(`brand: tail clearance ${TAIL_GAP}s; tracking ${TRACKING}em`)
console.log(
  `brand: whitespace in s: ${['tail-u', 'u-a', 'a-l', 'l-y'].map((pair, at) => `${pair} ${layout.gaps[at]!.toFixed(3)}`).join(', ')}`,
)
console.log(`brand: wordmark viewBox ${layout.viewBox}`)
for (const [file] of written) console.log(`brand: wrote packages/web/brand/${file}`)
